void mqttPong(String payload);
void connectWifi();
void connectMQTT();
double mapDouble(double x, double in_min, double in_max, double out_min, double out_max);
void mqttBUTTONState(String payload, int button);
void mqttSendBUTTON(String payload, int button);
void BUTTON1InterruptHandler();
void BUTTON2InterruptHandler();
void BUTTON3InterruptHandler();
void BUTTON4InterruptHandler();
void TWO_WAY_SWITCHInterruptHandler(void);
void mqttSendTWO_WAY_SWITCH (void);
void COVERInterruptHandler();
void mqttSendCOVER(void);
void LIGHTInterruptHandler();
void SONOFFInterruptHandler();
void mqttSONOFFSet(String payload) ;
void mqttCoverTrigger(void);
void mqttRelaySet(String payload, int relay);
float getDsTemp();
bool WiFiConnected (void);
bool MQTTConnected (void);
void mqttSend (char *topic, String message);
void mqttPublishSensorValues();
void mqttPublishStateValues();
void mqttPublishDisplayValues();
char* buildTopic(const char *topic);
void mqttSendBUTTON(String payload, int button);
